theme: jekyll-theme-slate
title: Welcome to ruaanviljoen's homepage!
description: Site still under construction, check back soon!

navigation:
- title: Home
  link: index.html
- title: Readme
  link: README.html
- title: contact.me
  link: contact.html

github_username:      ruaanviljoen
linkedin_username:    ruaan-viljoen-7931127b

plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
